---
- name: Install Redis for CentOS7
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ redis_packages_centos7 }}"
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7

- name: Install Redis for Ubuntu
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ redis_packages_ubuntu }}"
  when: ansible_os_family == 'Debian'
