---
- name: Install nginx from yum
  yum:
    name: nginx
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install nginx from apt-get
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
