---
- name: configure sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    backrefs: yes 
    owner: root
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#?\s*PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^#?\s*PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  when: ansible_os_family == 'RedHat'
